apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/salaboy/activiti-cloud-connector-slack:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/salaboy/activiti-cloud-connector-slack:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: activiti-cloud-connector-slack
        chartPath: charts/activiti-cloud-connector-slack
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/salaboy/activiti-cloud-connector-slack"
          image.tag: "{{.DIGEST_HEX}}"
